### ISSUE TITLE
Some PNG filenames do not match database names (Sega - Master System - Mark III)

### ISSUE THREAD

**Issue by yo6snap** [libretro-thumbnails/Sega_-_Master_System_-_Mark_III#6]
Some PNG filenames do not match database names in Sega - Master System - Mark III thumbnails directory. 

For now, I've done the renaming work with one game: Zillion.
(See this [pull request](https://github.com/libretro-thumbnails/Sega_-_Master_System_-_Mark_III/pull/5))

I can continue this work in `Sega - Master System - Mark III` directory if you are OK.

Below I began a list of games with naming problems:

## Choplifter
No-intro name: "Choplifter (USA, Europe, Brazil)"

Named_Titles, Named_Boxarts candidates:
- "Choplifter (Japan) (Proto).png"
- "Choplifter (USA) (Beta).png"
- "Choplifter (USA, Europe).png"

**KO**

_Remark: May you consider these white box [scans](http://www.smspower.org/Scans/Choplifter-SMS)? These boxes are more popular according to retro covers databases (SMSPower, segaretro ...)_

Named_Snaps candidates:
- "Choplifter (Japan) (Proto).png"
- "Choplifter (USA) (Beta).png"
- "Choplifter (USA, Europe).png"
- **"Choplifter (USA, Europe, Brazil).png" => Match no-intro name**

**OK**

## Enduro Racer
No-intro name: "Enduro Racer ~ Super Cross (USA, Europe, Brazil)"

Named_Titles, Named_Boxarts candidates:
- "Enduro Racer (Japan).png"
- "Enduro Racer (USA, Europe).png"

**KO**

Named_Snaps candidates:
- "Enduro Racer (Japan).png"
- "Enduro Racer (USA, Europe).png"
- **"Enduro Racer ~ Super Cross (USA, Europe, Brazil).png" => Match no-intro name**

**OK**

## Fantasy Zone II
No-intro name: "Fantasy Zone II (USA, Europe, Brazil)"

Named_Titles, Named_Boxarts candidates:
- "Fantasy Zone II - Opa-Opa no Namida (Japan).png"
- "Fantasy Zone II - The Tears of Opa-Opa (USA, Europe).png"

**KO**

_Remark: May you consider these white box [scans](http://www.smspower.org/Scans/FantasyZoneII-SMS)? These boxes are more popular according to retro covers databases (SMSPower, segaretro ...)_

Named_Snaps candidates:
- **"Fantasy Zone II (USA, Europe, Brazil).png" => Match no-intro name**
- "Fantasy Zone II - Opa-Opa no Namida (Japan).png"
- "Fantasy Zone II - The Tears of Opa-Opa (USA, Europe).png"

**OK**

## Gangster Town
No-intro name: "Gangster Town (USA, Europe, Brazil)"

Named_Titles, Named_Boxarts candidate: "Gangster Town (USA, Europe).png" **KO**

Named_Snaps candidates:
- "Gangster Town (USA, Europe).png"
- **"Gangster Town (USA, Europe, Brazil).png" => Match no-intro name**

**OK**

## Ghost House
No-intro name : "Ghost House (USA, Europe, Brazil)"

Named_Titles, Named_Boxarts candidates:
- "Ghost House (Japan).png"
- "Ghost House (USA, Europe) (Beta).png"
- "Ghost House (USA, Europe).png"

**KO**

Named_Snaps candidates:
- "Ghost House (Japan).png"
- "Ghost House (USA, Europe) (Beta).png"
- "Ghost House (USA, Europe).png"
- **"Ghost House (USA, Europe, Brazil).png" => Match no-intro name**

**OK**

## Hang On
No-intro name: "Hang On (Europe)"

Named_Titles, Named_Boxarts candidates:
- "Hang-On (Europe).png"
- "Hang-On (Japan).png"

**KO**

Named_Snaps candidates:
- **"Hang On (Europe).png" => Match no-intro name**
- "Hang-On (Europe).png"
- "Hang-On (Japan).png"

**OK**

## Zillion
No-intro name: "Zillion (USA, Europe) (Rev 1)"

Named_Titles, Named_Boxarts candidates:
- "Zillion (Europe) (Rev 2).png"
- "Zillion (Japan, Europe) (En,Ja).png"
- "Zillion (USA) (Rev 1).png"

**KO**

Named_Snaps candidates:
- "Zillion (Europe) (Rev 2).png"
- "Zillion (Europe, Brazil) (Rev 2).png"
- "Zillion (Japan, Europe) (En,Ja).png"
- "Zillion (USA) (Rev 1).png"

**KO**

**Comment by Hawaka743** [comment]
**This is a known issue.** Changes were made to the names in the databases, but some of the thumbnails haven't been renamed yet. In certain cases images with the new names have been uploaded, but the old ones (with the now incorrect names) weren't removed.

**In the** Retroarch **Database** certain **versions of a game now share one playlist name** (pl. a game has separate versions released in France and the rest of Europe, but the database only lists one name twice ending with (Europe)), example:

[There are 4 region versions of "Harry Potter & The Philosopher's Stone (Europe)" on the PS1. 
They all have different checksum values since the contents don't match 
(It is the same game, but translated into different languages (En,Fr,De - En,Nl,Da - Es,It,Pt - Sv,No,Fi)). 
Since they are all versions released in the European region, having even the same boxart (minus the subtitle being in a different language), there is no point in having 4 different playlist names and 4 boxarts, so they share the same one, and only need one image for the boxart.]

**Comment by Hawaka743** [comment]
I think no one is going to object. **Feel free to continue.**

Note: some game names include special characters (like the Harry Potter game above, "&"), these need to be replaced in the name of the thumbnails (Harry Potter _ The Philosopher's Stone (Europe)).

"libretro-thumbnails-check" shows the thumbnail names as they are supposed to be.

I usually check the names for the games in Retroarch's database viewer first, and then look at the names in the "libretro-thumbnails-check" (that one also shows the old names, which is why I check in Retroarch first).

**Comment by yo6snap** [comment]
Thanks for your replies!

I've read additional informations about libretro-thumbnails [here](https://github.com/libretro-thumbnails/libretro-thumbnails/blob/master/README.md).

For now, I'm waiting for someone which review my corresponding [pull request](https://github.com/libretro-thumbnails/Sega_-_Master_System_-_Mark_III/pull/5). I would like to check with reviewer if it is OK, and then I will correct game thumbnails of this issue in same way. 
Maybe @RobLoach ?

**Comment by RobLoach** [comment]
Thanks for checking these out! Would love some updates pushed forwards :+1:

**Comment by yo6snap** [comment]
@RobLoach I've just created a [Pull Request](https://github.com/libretro-thumbnails/Sega_-_Master_System_-_Mark_III/pull/8) in order to close this issue. 
As Zillion was merged before, It remains thumbnails of 6 games to merge (included in this pull request)
